app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('index');
});

// Login
Route::get('login/index', ['as' => 'login.index', 'uses' => 'Auth\LoginController@index']);
Route::post('login', ['as' => 'login.login', 'uses' => 'Auth\LoginController@login']);
Route::get('login/logout', ['as' => 'login.logout', 'uses' => 'Auth\LoginController@logout']);

// Sign Up
Route::resource('sign-up', 'Auth\SignUpController');
Route::get('account/verify/{code}', ['as' => 'account.verify','uses' => 'Auth\SignUpController@confirmAccount']);

// Search
Route::get('search/topic', ['as' => 'search.topic', 'uses' => 'SearchController@searchTopic']);

// Home
Route::get('home/{orderBy?}/{order?}', ['as' => 'home.index', 'uses' => 'HomeController@index']);

// Topic
Route::get('topic/{id}/create-resource', ['as' => 'topic.create_resource', 'uses' => 'TopicController@createResource']);
Route::get('topic/{id}/{orderBy?}/{order?}', ['as' => 'topic.show', 'uses' => 'TopicController@showTopic']);

// Pinner
Route::get('pinner/{id}/pin', ['as' => 'pinner.pin', 'uses' => 'PinnerController@pin']);
Route::get('pinner/{id}/unpin', ['as' => 'pinner.unpin', 'uses' => 'PinnerController@unpin']);

// Resource
Route::get('resource/{id}', ['as' => 'resource.show', 'uses' => 'ResourceController@showResource']);
Route::post('resource/{id}', ['as' => 'resource.store', 'uses' => 'ResourceController@submitResource']);
Route::post('resource/{id}/comment', ['as' => 'resource.comment.store', 'uses' => 'ResourceController@addComment']);

// Upvoter
Route::get('upvoter/{id}/upvote', ['as' => 'upvoter.upvote', 'uses' => 'UpvoterController@upvote']);

// Suggested Topic
Route::get('suggested-topic/create', ['as' => 'suggested_topic.create', 'uses' => 'SuggestedTopicController@create']);
Route::post('suggested-topic', ['as' => 'suggested_topic.store', 'uses' => 'SuggestedTopicController@suggestTopic']);

/* --- Web services ---- */

// Login
Route::post('ws/login', ['uses' => 'WebServiceController@login']);

// Resource
Route::post('ws/resources', ['uses' => 'WebServiceController@getAllResources']);
Route::post('ws/resource/{id}', ['uses' => 'WebServiceController@getResources']);

// Topic
Route::post('ws/topic/{id}', ['uses' => 'WebServiceController@getTopic']);

// Pinned Topics
Route::post('ws/pinned-topics/{id}', ['uses' => 'WebServiceController@getPinnedTopics']);

Route::post('api/test', ['uses' => 'WebServiceController@testAPI']);

resources/views/index.blade.php
@extends('layout.index')

@section('title')
    Login
@stop

@section('content')
    <section class="login">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    @if(Session::has('verification-message'))
                        <div class="form-group alert alert-success">
                            <p><i class="fa fa-check fa-lg fa-fw"></i>{{ session('verification-message') }}</p>
                        </div>
                    @elseif(Session::has('invalid-account-message'))
                        <div class="form-group alert alert-danger">
                            <p><i class="fa fa-times fa-lg fa-fw"></i>{{ session('invalid-account-message') }}</p>
                        </div>
                    @endif
                    <div class="form-default form-login">
                        <form action="{{ route('login.login') }}" method="post" role="form">
                            {!! csrf_field() !!}
                            <div class="form-group text-center">
                                <h4><strong>Login</strong></h4>
                            </div>
                            <div class="form-group">
                                <input class="form-control"
                                       id="email"
                                       type="text"
                                       name="email"
                                       value="{{old('email')}}"
                                       placeholder="Email">
                                <p class="help-block msg-error">
                                @foreach($errors->get('email') as $error)
                                    {{$error}}
                                @endforeach
                                </p>
                            </div>
                            <div class="form-group">
                                <input class="form-control"
                                       id="password"
                                       type="password"
                                       name="password"
                                       value="{{old('password')}}"
                                       placeholder="Password">
                                <p class="help-block msg-error">
                                @foreach($errors->get('password') as $error)
                                    {{$error}}
                                @endforeach
                                </p>
                            </div>
                            <div class="form-group text-center">
                                <button class="btn btn-default" type="submit">Login</button>
                            </div>
                        </form>

                        <div>
                            <a href="#" class="small link-blue">Forgot Password?</a>
                            <a href="{{ route('sign-up.index') }}" class="small link-blue pull-right">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@stop